site.name: "Lobocode Labs"
highlighter: rouge
markdown: kramdown
exclude:
- node_modules
- vendor

navigation:
- text: Home
  url: /index.html
- text: About
  url: /about/index.html
- text: Projects
  url: /projects/index.html

